const {
  DB_USER,
  DB_PASS,
  DB_NAME,
  DB_HOST,
  DB_PORT,
  NODE_ENV,
  SERVER_PORT,
  SSL_CERTIFICATE_KEY_PATH,
  SSL_CERTIFICATE_CRT_PATH,
} = process.env;

export default {
  IS_PRODUCTION: NODE_ENV !== 'development',
  DB_HOST,
  DB_PORT: DB_PORT ? Number.parseInt(DB_PORT) : 5432,
  DB_USER,
  DB_NAME,
  DB_PASS,
  SERVER_PORT: SERVER_PORT ? Number.parseInt(SERVER_PORT) : 3001,
  SSL_CERTIFICATE_KEY_PATH: SSL_CERTIFICATE_KEY_PATH || '',
  SSL_CERTIFICATE_CRT_PATH: SSL_CERTIFICATE_CRT_PATH || '',
};
